services:
  bm-backend:
    image: gcr.io/brawlmanager/brawlmanager-backend
    build:
      context: ./bm-backend
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - db

  bm-frontend:
    image: gcr.io/brawlmanager/brawlmanager-frontend
    build:
      context: ./bm-frontend
      dockerfile: dockerfile.prod
      args:
        - REACT_APP_API_URL
    environment:
      - PORT=3000
    env_file: .env
    #volumes:
    #  - ./bm-frontend:/app
    #  - /app/node_modules # Ensures node_modules don't get overwritten by the host
    ports:
      - "3000:3000"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: brawlmanagerdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
