services:
  # Backend Service - Production
  bm-backend:
    profiles: ["prod"]
    image: gcr.io/brawlmanager/brawlmanager-backend
    build:
      context: ./bm-backend
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - db

  # Backend Service - Development
  bm-backend-dev:
    profiles: ["dev"]
    image: gcr.io/brawlmanager/brawlmanager-backend-dev
    build:
      context: ./bm-backend
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./bm-backend:/app
    depends_on:
      - db

  # Frontend Service - Production
  bm-frontend:
    profiles: ["prod"]
    image: gcr.io/brawlmanager/brawlmanager-frontend
    build:
      context: ./bm-frontend
      dockerfile: dockerfile.prod
      args:
        - REACT_APP_API_URL
    environment:
      - PORT=3000
    env_file: .env
    ports:
      - "3000:3000"

  # Frontend Service - Development
  bm-frontend-dev:
    profiles: ["dev"]
    image: gcr.io/brawlmanager/brawlmanager-frontend-dev
    build:
      context: ./bm-frontend
      dockerfile: dockerfile.dev
      args:
        - REACT_APP_API_URL
    environment:
      - PORT=3000
    env_file: .env
    volumes:
      - ./bm-frontend:/app
      - /app/node_modules # Ensures node_modules don't get overwritten by the host
    ports:
      - "3000:3000"

  # Database Service
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: brawlmanagerdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
