# Example Dockerfile for bm-backend

# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Install any needed packages specified in requirements.txt
COPY requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . /app


# Expose the port the app runs on
ENV PORT=8000
EXPOSE 8080

# Run the application
CMD uvicorn app.main:app --host 0.0.0.0 --port $PORT --reload
