# Frontend Dockerfile

FROM node:14

WORKDIR /app

COPY package.json /app/
COPY package-lock.json /app/
RUN npm install

COPY ./ /app/

RUN npm run build

# The EXPOSE instruction is optional and is mostly for documentation purposes.
EXPOSE 3000

# Use the PORT environment variable if it exists, or default to 3000
CMD ["sh", "-c", "serve -s build -l ${PORT:-3000}"]