# Development Dockerfile

# Use a Node base image
FROM node:14

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json
COPY package.json /app/
COPY package-lock.json /app/

# Install dependencies
RUN npm install

# Define build argument and environment variable for API URL
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=${REACT_APP_API_URL}

# Expose the development server port (default is 3000)
EXPOSE 3000

# Copy the entire app code into the container
COPY . /app/

# Start the development server with hot reloading
CMD ["npm", "start"]