# Frontend Dockerfile

FROM node:14

WORKDIR /app

COPY package.json /app/
COPY package-lock.json /app/
RUN npm install

COPY . /app/

RUN npm run build
# Install 'serve' globally
RUN npm install -g serve

# Expose the port the app runs on
ENV PORT=3000
EXPOSE 8080

# Use the PORT environment variable if it exists
CMD ["sh", "-c", "serve -s build -l ${PORT}"]